# -*- coding: utf-8 -*-
"""water_fish.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIt5Kaj9olKDxRJvbWFTA6HKHbdjeDHn
"""

#Water_fish

import zipfile
import os

# Path to your uploaded zip file in Google Colab
zip_file_path = '/content/aquarium_fish.zip'
extract_folder = '/content/dataset/'

# Unzip the dataset
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_folder)

print("Dataset extracted successfully!")

!pip install ultralytics

from ultralytics import YOLO

# Load a YOLOv11n pre-trained model (replace with correct path if needed)
model = YOLO("yolo11n.pt")

from ultralytics import YOLO

# Load a pre-trained YOLOv11 model (or YOLOv5 model if using that)
model = YOLO("yolo11n.pt")  # Replace with the correct model weights file

# Train the model using your custom dataset
results = model.train(data="/content/dataset/aquarium_fish/data.yaml", epochs=10, imgsz=640)

# Print training results
print(results)

from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Run inference
results = model('/content/dataset/aquarium_fish/train/images/IMG_2274_jpeg_jpg.rf.2f319e949748145fb22dcb52bb325a0c.jpg')  # Replace with your test image path
if results:
  # Display the first detection (if available)
  # Modify this logic to iterate and display all detections if needed
  results[0].show()
else:
  print("No objects detected in the image.")